In [4]:
import numpy as np
from scipy.linalg import circulant, toeplitz

In [5]:
x = (np.arange(4) * 2 + 1).reshape((2, 2))
# x = np.asarray([[0, 1, 0, 0, 2],
#                 [1, 2, 2, 0, 0],
#                 [0, 0, 2, 1, 1],
#                 [1, 2, 0, 0, 1],
#                 [0, 0, 0, 1, 1]])
x

array([[1, 3],
       [5, 7]])

In [6]:
w = (np.arange(4) + 10).reshape((2, 2))
# w = np.asarray([[-1, 1, 0],
#                 [0, 1, 0],
#                 [-1, 1, -1]])
w

array([[10, 11],
       [12, 13]])

In [7]:
x = np.pad(x, 1, 'constant')
n_rows_in_x, n_columns_in_x = x.shape
x = x.reshape((-1))
n_elements_in_x = len(x)
n_rows_in_w, n_columns_in_w = w.shape

In [8]:
f = np.zeros((n_rows_in_x, n_columns_in_x))
f[:n_rows_in_w, :n_columns_in_w] = w
f = f.reshape(-1)
f

array([10., 11.,  0.,  0., 12., 13.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.])

In [9]:
w_ = circulant(f).T
w_

array([[10., 11.,  0.,  0., 12., 13.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0., 10., 11.,  0.,  0., 12., 13.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0., 10., 11.,  0.,  0., 12., 13.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0., 10., 11.,  0.,  0., 12., 13.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 10., 11.,  0.,  0., 12., 13.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 10., 11.,  0.,  0., 12., 13.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., 10., 11.,  0.,  0., 12., 13.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 10., 11.,  0.,  0., 12., 13.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10., 11.,  0.,  0., 12.,
        13.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10., 11.,  0.,  0.,
        12., 13.,  0.],
       [ 0.,  0.,  0.,  0.,  0

In [7]:
print(w_)

[[10. 11.  0.  0. 12. 13.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 10. 11.  0.  0. 12. 13.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10. 11.  0.  0. 12. 13.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10. 11.  0.  0. 12. 13.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 10. 11.  0.  0. 12. 13.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 10. 11.  0.  0. 12. 13.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 10. 11.  0.  0. 12. 13.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 10. 11.  0.  0. 12. 13.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 10. 11.  0.  0. 12. 13.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 10. 11.  0.  0. 12. 13.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10. 11.  0.  0. 12. 13.]
 [13.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10. 11.  0.  0. 12.]
 [12. 13.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10. 11.  0.  0.]
 [ 0. 12. 13.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10. 11.  0.]
 [ 0.  0. 12. 13.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10. 

In [8]:
w_.shape

(16, 16)

In [9]:
stride = 1
n_rows_in_output = int(np.floor((n_rows_in_x - n_rows_in_w) / stride + 1))
n_columns_in_output = int(np.floor((n_columns_in_x - n_columns_in_w) / stride + 1))

indices = np.zeros(w_.shape[0], dtype=bool)
for index_row, index_start in enumerate(range(0, indices.shape[0], n_columns_in_x)):
    if index_row >= n_rows_in_output:
        break
    index_end = index_start + n_columns_in_output
    indices[index_start:index_end] = [True] * n_columns_in_output

if n_rows_in_output * n_columns_in_output != np.sum(indices):
    raise Exception('Sum of indices should match the values in output')
indices

array([ True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True, False, False, False, False, False])

In [10]:
w_result = w_[indices, :]
w_result

array([[10., 11.,  0.,  0., 12., 13.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0., 10., 11.,  0.,  0., 12., 13.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0., 10., 11.,  0.,  0., 12., 13.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 10., 11.,  0.,  0., 12., 13.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 10., 11.,  0.,  0., 12., 13.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., 10., 11.,  0.,  0., 12., 13.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10., 11.,  0.,  0., 12.,
        13.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10., 11.,  0.,  0.,
        12., 13.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10., 11.,  0.,
         0., 12., 13.]])

In [22]:
goal = [[10, 11, 0, 0, 12, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 10, 11, 0, 0, 12, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 10, 11, 0, 0, 12, 13, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 10, 11, 0, 0, 12, 13, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 10, 11, 0, 0, 12, 13, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 10, 11, 0, 0, 12, 13, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 10, 11, 0, 0, 12, 13, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 11, 0, 0, 12, 13, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 11, 0, 0, 12, 13]]
goal

[[10, 11, 0, 0, 12, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 10, 11, 0, 0, 12, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 10, 11, 0, 0, 12, 13, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 10, 11, 0, 0, 12, 13, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 10, 11, 0, 0, 12, 13, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 10, 11, 0, 0, 12, 13, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 10, 11, 0, 0, 12, 13, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 11, 0, 0, 12, 13, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 11, 0, 0, 12, 13]]

In [23]:
np.sum(w_result - goal != 0)

NameError: name 'w_result' is not defined

In [13]:
result_mine = (w_result @ x).reshape((3, 3))
# result_mine = (w_result @ x).reshape((5, 5))
result_mine

array([[ 13.,  51.,  36.],
       [ 76., 194., 114.],
       [ 55., 127.,  70.]])

In [14]:
import numpy as np
import torch.nn as nn

c = nn.Conv2d(1, 1, kernel_size=2, padding=1, stride=1, bias=False)
c.weight.data[0, 0, 0, 0] = 10
c.weight.data[0, 0, 0, 1] = 11
c.weight.data[0, 0, 1, 0] = 12
c.weight.data[0, 0, 1, 1] = 13

# c = nn.Conv2d(1, 1, kernel_size=3, padding=1, stride=1, bias=False)
# c.weight.data[0, 0, 0, 0] = -1
# c.weight.data[0, 0, 0, 1] = 1
# c.weight.data[0, 0, 0, 2] = 0
# c.weight.data[0, 0, 1, 0] = 0
# c.weight.data[0, 0, 1, 1] = 1
# c.weight.data[0, 0, 1, 2] = 0
# c.weight.data[0, 0, 2, 0] = -1
# c.weight.data[0, 0, 2, 1] = 1
# c.weight.data[0, 0, 2, 2] = -1
c.weight.data


(0 ,0 ,.,.) = 
  10  11
  12  13
[torch.FloatTensor of size 1x1x2x2]

In [15]:
import torch
from torch.autograd import Variable

x_2 = (np.arange(4) * 2 + 1).reshape((2, 2)) 

# x_2 = np.asarray([[0, 1, 0, 0, 2],
#                   [1, 2, 2, 0, 0],
#                   [0, 0, 2, 1, 1],
#                   [1, 2, 0, 0, 1],
#                   [0, 0, 0, 1, 1]])
x_2 = Variable(torch.from_numpy(x_2[None, None, ...]))
x_2 = x_2.float()
x_2

Variable containing:
(0 ,0 ,.,.) = 
  1  3
  5  7
[torch.FloatTensor of size 1x1x2x2]

In [16]:
result_pytorch = c(x_2)
result_pytorch = result_pytorch.cpu().data.numpy()
result_pytorch = np.squeeze(result_pytorch)
result_pytorch

array([[ 13.,  51.,  36.],
       [ 76., 194., 114.],
       [ 55., 127.,  70.]], dtype=float32)

In [17]:
np.sum(result_pytorch - result_mine != 0)

0

In [2]:
import numpy as np

x = (np.arange(4) * 2 + 1).reshape((2, 2))
x = np.pad(x, 1, 'constant')
n_rows_in_x, n_columns_in_x = x.shape
x = x.reshape((-1))

In [3]:
w = (np.arange(4) + 10).reshape((2, 2))
# w = csr_matrix(w)
n_elements_in_x = len(x)
n_rows_in_w, n_columns_in_w = w.shape

In [13]:
from scipy.sparse import csr_matrix

w_

array([[10., 11.,  0.,  0., 12., 13.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0., 10., 11.,  0.,  0., 12., 13.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0., 10., 11.,  0.,  0., 12., 13.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0., 10., 11.,  0.,  0., 12., 13.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 10., 11.,  0.,  0., 12., 13.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 10., 11.,  0.,  0., 12., 13.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., 10., 11.,  0.,  0., 12., 13.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 10., 11.,  0.,  0., 12., 13.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10., 11.,  0.,  0., 12.,
        13.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10., 11.,  0.,  0.,
        12., 13.,  0.],
       [ 0.,  0.,  0.,  0.,  0

In [17]:
w_2 = csr_matrix(w_)

In [18]:
stride = 1
n_rows_in_output = int(np.floor((n_rows_in_x - n_rows_in_w) / stride + 1))
n_columns_in_output = int(np.floor((n_columns_in_x - n_columns_in_w) / stride + 1))

indices = np.zeros(w_.shape[0], dtype=bool)
for index_row, index_start in enumerate(range(0, indices.shape[0], n_columns_in_x)):
    if index_row >= n_rows_in_output:
        break
    index_end = index_start + n_columns_in_output
    indices[index_start:index_end] = [True] * n_columns_in_output

if n_rows_in_output * n_columns_in_output != np.sum(indices):
    raise Exception('Sum of indices should match the values in output')
indices

array([ True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True, False, False, False, False, False])

In [20]:
w_result_2 = w_2[indices, :]
w_result_2.toarray()

array([[10., 11.,  0.,  0., 12., 13.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0., 10., 11.,  0.,  0., 12., 13.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0., 10., 11.,  0.,  0., 12., 13.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 10., 11.,  0.,  0., 12., 13.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 10., 11.,  0.,  0., 12., 13.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., 10., 11.,  0.,  0., 12., 13.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10., 11.,  0.,  0., 12.,
        13.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10., 11.,  0.,  0.,
        12., 13.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10., 11.,  0.,
         0., 12., 13.]])

In [24]:
np.sum(w_result_2.toarray() - goal != 0)

0